#include "Valorant/Output.h"
#include "Valorant/Decryption.h"

#include "OffsetFinder/Offsets.h"
#include "Settings.h"

#include <fstream>
#include <iostream>

namespace Valorant
{
    // Placeholders for offsets that need per-patch signature scanning. Each
    // entry stays 0 until the matching locator is added next to the existing
    // GObjects locator in Decryption.cpp.
    //
    // The other reference dumper auto-discovers these via:
    //   * UE-standard signatures        (StaticFindObject, StaticLoadObject, FMemoryMalloc)
    //   * Valorant-only string anchors  (PlayFinisher, SetOutlineMode, GetSpread*)
    //   * vtable/xref pattern scans     (BoneMatrix, ToVector/AngleNormalize, GetFiringLocAndDir)
    namespace TodoOffsets
    {
        // Game / engine function pointers (RVA from module base). Filled by
        // per-patch signature scans next to Valorant::FindGObjects.
        //
        // The reference dumper auto-discovers these via:
        //   * UE-standard signatures        (StaticFindObject, StaticLoadObject, FMemoryMalloc)
        //   * Valorant-only string anchors  (PlayFinisher, SetOutlineMode, GetSpread*)
        //   * vtable/xref pattern scans     (BoneMatrix, ToVector/AngleNormalize, GetFiringLocAndDir)
        constexpr uint32_t kStaticFindObject     = 0;
        constexpr uint32_t kStaticLoadObject     = 0;
        constexpr uint32_t kFMemoryMalloc        = 0;
        constexpr uint32_t kBoneMatrix           = 0;
        constexpr uint32_t kSetOutlineMode       = 0;
        constexpr uint32_t kPlayFinisher         = 0;
        constexpr uint32_t kGetSpreadValues      = 0;
        constexpr uint32_t kGetSpreadAngles      = 0;
        constexpr uint32_t kToVectorNormalize    = 0;
        constexpr uint32_t kToAngleNormalize     = 0;
        constexpr uint32_t kGetFiringLocAndDir   = 0;
    }

    void WriteDecryptHeader(const fs::path& OutputFolder)
    {
        const fs::path target = OutputFolder / "ValorantDecrypt.h";

        std::ofstream out(target);
        if (!out.is_open())
        {
            std::cerr << "[Valorant] Failed to open " << target << " for write.\n";
            return;
        }

        out << "#pragma once\n\n";
        out << "#include <cstdint>\n\n";

        out << "/*\n";
        out << " * ValorantDecrypt.h\n";
        out << " *\n";
        out << " * Generated by Dumper-7-VGK alongside the SDK. Collects every\n";
        out << " * RVA + decrypt routine a consumer (ESP, internal tool, etc.)\n";
        out << " * needs to use the SDK against the live game.\n";
        out << " *\n";
        out << " * Offset sources:\n";
        out << " *   - GObjects state/key:  hardcoded in Dumper-7-VGK Decryption.h\n";
        out << " *   - GWorld, FNamePool,   auto-discovered by upstream Dumper-7\n";
        out << " *     AppendString, PE     pattern scans\n";
        out << " *   - FName decrypt + the  TODO — locate per patch, see source\n";
        out << " *     game function ptrs   for the planned scan strategies\n";
        out << " *\n";
        out << " * Build: " << Settings::Generator::GameVersion << "-"
                            << Settings::Generator::GameName << "\n";
        out << " */\n\n";

        out << "namespace ValorantSDK\n";
        out << "{\n\n";

        // ---------- Global pointers ----------
        out << "/* --- Global Pointers (RVA from module base) --- */\n";
        out << "constexpr uint32_t GWorld              = 0x" << std::hex
            << Off::InSDK::World::GWorld << std::dec << ";  // 0 if Riot stripped the static slot\n";
        out << "constexpr uint32_t FNamePool           = 0x" << std::hex
            << Off::InSDK::NameArray::GNames << std::dec << ";\n";
        out << "constexpr uint32_t GObjectsState       = 0x" << std::hex
            << Valorant::kGObjectsStateRVA << std::dec << ";  // 7 qwords\n";
        out << "constexpr uint32_t GObjectsKey         = 0x" << std::hex
            << Valorant::kGObjectsKeyRVA << std::dec << ";   // uint32\n";
        out << "constexpr int32_t  ProcessEventIndex   = " << std::dec
            << Off::InSDK::ProcessEvent::PEIndex << ";\n\n";

        out << "// FName decrypt: this Valorant patch uses a simple per-byte XOR with a\n";
        out << "// single 32-bit key recovered from the \"None\" entry's known plaintext.\n";
        out << "// No static state/key RVA to embed — call recover_fname_key() below.\n";
        out << "// (A future patch may reintroduce a 7-state mask cipher; if so, add the\n";
        out << "// state/key RVAs here and port the case math to fname_decrypt_mask().)\n\n";

        // ---------- Function pointers ----------
        out << "/* --- Function Pointers (RVA from module base) --- */\n";
        out << "constexpr uint32_t ProcessEvent        = 0x" << std::hex
            << Off::InSDK::ProcessEvent::PEOffset << std::dec << ";\n";
        out << "constexpr uint32_t AppendString        = 0x" << std::hex
            << Off::InSDK::Name::AppendNameToString << std::dec << ";\n";
        out << "constexpr uint32_t StaticFindObject    = 0x" << std::hex
            << TodoOffsets::kStaticFindObject << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t StaticLoadObject    = 0x" << std::hex
            << TodoOffsets::kStaticLoadObject << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t FMemoryMalloc       = 0x" << std::hex
            << TodoOffsets::kFMemoryMalloc << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t BoneMatrix          = 0x" << std::hex
            << TodoOffsets::kBoneMatrix << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t SetOutlineMode      = 0x" << std::hex
            << TodoOffsets::kSetOutlineMode << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t PlayFinisher        = 0x" << std::hex
            << TodoOffsets::kPlayFinisher << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t GetSpreadValues     = 0x" << std::hex
            << TodoOffsets::kGetSpreadValues << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t GetSpreadAngles     = 0x" << std::hex
            << TodoOffsets::kGetSpreadAngles << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t ToVectorNormalize   = 0x" << std::hex
            << TodoOffsets::kToVectorNormalize << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t ToAngleNormalize    = 0x" << std::hex
            << TodoOffsets::kToAngleNormalize << std::dec << ";  // TODO\n";
        out << "constexpr uint32_t GetFiringLocAndDir  = 0x" << std::hex
            << TodoOffsets::kGetFiringLocAndDir << std::dec << ";  // TODO\n\n";

        // ---------- GObjects decrypt body ----------
        out << "/* --- GObjects Decrypt (ported from sub_EA1980) --- */\n\n";

        out << "__forceinline uint64_t rol64(uint64_t v, uint32_t n)\n";
        out << "{\n";
        out << "    n &= 63;\n";
        out << "    if (n == 0) return v;\n";
        out << "    return (v << n) | (v >> (64 - n));\n";
        out << "}\n\n";

        out << "__forceinline uint64_t ror64(uint64_t v, uint32_t n)\n";
        out << "{\n";
        out << "    n &= 63;\n";
        out << "    if (n == 0) return v;\n";
        out << "    return (v >> n) | (v << (64 - n));\n";
        out << "}\n\n";

        out << "__forceinline uint64_t stage1(uint64_t v) { return (v >> 1) ^ (((v >> 1) ^ (v << 1)) & 0xAAAAAAAAAAAAAAAAULL); }\n";
        out << "__forceinline uint64_t stage2(uint64_t v) { return (v >> 2) ^ (((v >> 2) ^ (v << 2)) & 0xCCCCCCCCCCCCCCCCULL); }\n";
        out << "__forceinline uint64_t stage3(uint64_t v) { return (v >> 4) ^ (((v >> 4) ^ (v << 4)) & 0xF0F0F0F0F0F0F0F0ULL); }\n";
        out << "__forceinline uint64_t stage4(uint64_t v) { return (v >> 8) ^ (((v >> 8) ^ (v << 8)) & 0xFF00FF00FF00FF00ULL); }\n";
        out << "__forceinline uint64_t bitrev64(uint64_t v) { return ror64(stage4(stage3(stage2(stage1(v)))), 32); }\n\n";

        out << "// Reads state[7] + key from the live module and returns the FUObjectArray base.\n";
        out << "__forceinline uint64_t decrypt_gobjects(uintptr_t module_base)\n";
        out << "{\n";
        out << "    constexpr uint64_t kMagic = 0x2545F4914F6CDD1DULL;\n";
        out << "    const uint64_t* statePtr = reinterpret_cast<const uint64_t*>(module_base + GObjectsState);\n";
        out << "    const uint32_t  key      = *reinterpret_cast<const uint32_t*>(module_base + GObjectsKey);\n";
        out << "    uint64_t state[7];\n";
        out << "    for (int i = 0; i < 7; ++i) state[i] = statePtr[i];\n\n";
        out << "    const uint32_t mix  = key ^ (((key ^ (key >> 15)) >> 12)) ^ (key << 25);\n";
        out << "    const uint64_t hash = kMagic * static_cast<uint64_t>(mix);\n";
        out << "    const uint32_t hi   = static_cast<uint32_t>(hash >> 32);\n";
        out << "    const uint32_t idx  = static_cast<uint32_t>(hash % 7ULL);\n";
        out << "    uint64_t v = state[idx];\n\n";
        out << "    switch (idx)\n";
        out << "    {\n";
        out << "    case 0:  v ^= static_cast<uint64_t>(hi); break;\n";
        out << "    case 1:  { uint32_t a = ((hi + 2 * idx) % 63) + 1; v = static_cast<uint64_t>(static_cast<uint32_t>(hi + idx)) + rol64(v, a); break; }\n";
        out << "    case 2:  v = (~v) - static_cast<uint64_t>(static_cast<uint32_t>(hi + idx)); break;\n";
        out << "    case 3:  { uint32_t a = ((hi + idx)     % 63) + 1; v = ror64(bitrev64(v), a); break; }\n";
        out << "    case 4:  v += static_cast<uint64_t>(static_cast<uint32_t>(hi + 2 * idx)) + static_cast<uint64_t>(static_cast<uint32_t>(hi + idx)); break;\n";
        out << "    case 5:  { uint32_t a = ((hi + idx)     % 63) + 1; v = rol64(stage1(v), a); break; }\n";
        out << "    case 6:  { uint32_t a = ((hi + idx)     % 63) + 1; v = ror64(static_cast<uint64_t>(static_cast<uint32_t>(hi + 2 * idx)) + v, a); break; }\n";
        out << "    }\n\n";
        out << "    return v ^ static_cast<uint64_t>(key);\n";
        out << "}\n\n";

        // ---------- FName decrypt body ----------
        out << "/* --- FName Per-Byte XOR Decrypt --- */\n\n";

        out << "// 'None' XOR-mask: 'N'^'o'^'n'^'e' bytes pre-shifted by the encoder's\n";
        out << "// length/position step. XOR'ing the encrypted first-entry name dword\n";
        out << "// against this constant recovers the FName key.\n";
        out << "constexpr uint32_t kFNameNoneMask = 0x616A6B4A;\n\n";

        out << "// Recover the FName XOR key from FNamePool's first entry (\"None\").\n";
        out << "// fname_pool_base is the value at *(module_base + FNamePool).\n";
        out << "__forceinline uint32_t recover_fname_key(uintptr_t fname_pool_base)\n";
        out << "{\n";
        out << "    const uintptr_t chunk0 = *reinterpret_cast<uintptr_t*>(fname_pool_base + 0x10);\n";
        out << "    if (!chunk0) return 0;\n";
        out << "    // First entry is \"None\" — its 4 encrypted name bytes start at +6 from\n";
        out << "    // the entry base; XOR with kFNameNoneMask gives the key.\n";
        out << "    const uintptr_t entry  = chunk0 + 12;  // header at +0..+5\n";
        out << "    const uint32_t  enc4   = *reinterpret_cast<uint32_t*>(entry + 6);\n";
        out << "    return enc4 ^ kFNameNoneMask;\n";
        out << "}\n\n";

        out << "// Decrypt an FName entry's bytes in place using a key recovered from\n";
        out << "// recover_fname_key(). buf must hold `len` bytes copied from\n";
        out << "// entry_address + 6 (after the 6-byte FName entry header).\n";
        out << "__forceinline void fname_decrypt_bytes(uint8_t* buf, uint16_t len, uint32_t key)\n";
        out << "{\n";
        out << "    for (uint16_t i = 0; i < len; ++i)\n";
        out << "    {\n";
        out << "        const uint8_t k = static_cast<uint8_t>((key >> ((i & 3) * 8)) & 0xFF);\n";
        out << "        buf[i] ^= static_cast<uint8_t>(len) ^ k;\n";
        out << "    }\n";
        out << "}\n\n";

        out << "} // namespace ValorantSDK\n";
        out.close();

        std::cerr << "[Valorant] Wrote " << target.string() << "\n";
    }
}
