#include "Valorant/Output.h"
#include "Valorant/Decryption.h"
#include "Valorant/FunctionLocator.h"

#include "OffsetFinder/Offsets.h"
#include "Settings.h"

#include "Json/json.hpp"

#include <fstream>
#include <iostream>
#include <chrono>
#include <iomanip>
#include <sstream>

namespace Valorant
{
    // Placeholders for offsets that need per-patch signature scanning. Each
    // entry stays 0 until the matching locator is added next to the existing
    // GObjects locator in Decryption.cpp.
    //
    // The other reference dumper auto-discovers these via:
    //   * UE-standard signatures        (StaticFindObject, StaticLoadObject, FMemoryMalloc)
    //   * Valorant-only string anchors  (PlayFinisher, SetOutlineMode, GetSpread*)
    //   * vtable/xref pattern scans     (BoneMatrix, ToVector/AngleNormalize, GetFiringLocAndDir)
    // Non-UFunction-backed offsets we still need per-patch signature scans for.
    // The 7 UFunction-reflected game functions (SetOutlineMode, PlayFinisher,
    // GetSpread*, GetFiringLocAndDir, ToVector/AngleNormalize) live in
    // Valorant::GameFunctions and are populated by LocateGameFunctions().
    // Forward declaration — defined later in this translation unit.
    void WriteOffsetsJson(const fs::path& OutputFolder);

    namespace TodoOffsets
    {
        constexpr uint32_t kStaticFindObject = 0x108DA10; // located: only fn with `aStaticfindfirs` data xref
        constexpr uint32_t kStaticLoadObject = 0;         // TODO: chase callers of StaticFindObject that hit FLinkerLoad
        constexpr uint32_t kFMemoryMalloc    = 0;         // TODO: GMalloc vtable path (qword_A1CC130)
        constexpr uint32_t kBoneMatrix       = 0;         // TODO: USkinnedMeshComponent native member, no UFunction
    }

    // Returns a UTC ISO-8601 timestamp string (e.g. "2026-05-16T12:34:56Z")
    // using only <chrono> and standard C library — no platform-specific helpers.
    static std::string GetUtcTimestamp()
    {
        const auto now      = std::chrono::system_clock::now();
        const std::time_t t = std::chrono::system_clock::to_time_t(now);

        std::tm utc{};
#if defined(_WIN32)
        gmtime_s(&utc, &t);
#else
        gmtime_r(&t, &utc);
#endif
        char buf[32];
        std::snprintf(buf, sizeof(buf), "%04d-%02d-%02dT%02d:%02d:%02dZ",
            utc.tm_year + 1900, utc.tm_mon + 1, utc.tm_mday,
            utc.tm_hour,        utc.tm_min,      utc.tm_sec);
        return buf;
    }

    // Helper: format a hex RVA as "0xABCDEF" string.
    static std::string HexRva(uint32_t rva)
    {
        std::ostringstream ss;
        ss << "0x" << std::hex << rva;
        return ss.str();
    }

    // Emit the /// source= metadata line for a constant, including optional
    // full_name (reflection) and drift warning (sigscan). Writes to `out`.
    static void EmitSourceLine(std::ostream& out,
                               const char*        source,
                               const std::string& fullName  = {},
                               bool               drift     = false,
                               uint32_t           fallback  = 0,
                               const char*        triedAlt  = nullptr)
    {
        out << "/// source=" << source;
        if (!fullName.empty())
            out << "  full_name=\"" << fullName << "\"";
        if (triedAlt)
            out << "  tried=[\"" << triedAlt << "\"]";
        if (drift)
        {
            out << "  fallback=" << HexRva(fallback)
                << "  DRIFT (bump Decryption.h fallback)";
        }
        out << "\n";
    }

    void WriteDecryptHeader(const fs::path& OutputFolder)
    {
        const fs::path target = OutputFolder / "ValorantDecrypt.h";

        std::ofstream out(target);
        if (!out.is_open())
        {
            std::cerr << "[Valorant] Failed to open " << target << " for write.\n";
            return;
        }

        // Pre-compute drift flags for GObjects sigscan entries.
        const bool gObjectsStateDrift = (Valorant::gObjectsStateRVA != Valorant::kGObjectsStateRVA);
        const bool gObjectsKeyDrift   = (Valorant::gObjectsKeyRVA   != Valorant::kGObjectsKeyRVA);

        out << "#pragma once\n\n";
        out << "#include <cstdint>\n\n";

        // ------------------------------------------------------------------ //
        // Header banner
        // ------------------------------------------------------------------ //
        out << "/*\n";
        out << " * ValorantDecrypt.h\n";
        out << " *\n";
        out << " * Generated by Dumper-7-VGK alongside the SDK. Collects every\n";
        out << " * RVA + decrypt routine a consumer (ESP, internal tool, etc.)\n";
        out << " * needs to use the SDK against the live game.\n";
        out << " *\n";
        out << " * Generated at: " << GetUtcTimestamp() << "\n";
        out << " *\n";
        out << " * Offset sources:\n";
        out << " *   - GObjects state/key:  hardcoded in Dumper-7-VGK Decryption.h\n";
        out << " *   - GWorld, FNamePool,   auto-discovered by upstream Dumper-7\n";
        out << " *     AppendString, PE     pattern scans\n";
        out << " *   - FName decrypt + the  TODO -- locate per patch, see source\n";
        out << " *     game function ptrs   for the planned scan strategies\n";
        out << " *\n";
        out << " * Build: " << Settings::Generator::GameVersion << "-"
                            << Settings::Generator::GameName << "\n";
        out << " */\n\n";

        out << "namespace ValorantSDK\n";
        out << "{\n\n";

        // ------------------------------------------------------------------ //
        // Global Pointers
        // ------------------------------------------------------------------ //
        out << "// ============== Global Pointers ==============\n\n";

        out << "/// RVA of UWorld* from the module base; 0 if Riot stripped the static slot.\n";
        EmitSourceLine(out, "stripped");
        out << "constexpr uint32_t GWorld            = 0x" << std::hex
            << Off::InSDK::World::GWorld << std::dec << ";\n";
        out << "/// RVA of the FNamePool root pointer from the module base.\n";
        EmitSourceLine(out, "upstream");
        out << "constexpr uint32_t FNamePool         = 0x" << std::hex
            << Off::InSDK::NameArray::GNames << std::dec << ";\n";
        out << "/// RVA of the 7-qword GObjects state array used by decrypt_gobjects().\n";
        EmitSourceLine(out, "sigscan", {}, gObjectsStateDrift, Valorant::kGObjectsStateRVA);
        out << "constexpr uint32_t GObjectsState     = 0x" << std::hex
            << Valorant::gObjectsStateRVA << std::dec << ";\n";
        out << "/// RVA of the uint32 GObjects key consumed by decrypt_gobjects().\n";
        EmitSourceLine(out, "sigscan", {}, gObjectsKeyDrift, Valorant::kGObjectsKeyRVA);
        out << "constexpr uint32_t GObjectsKey       = 0x" << std::hex
            << Valorant::gObjectsKeyRVA << std::dec << ";\n";
        out << "/// Vtable index of UObject::ProcessEvent (zero-based).\n";
        EmitSourceLine(out, "upstream");
        out << "constexpr int32_t  ProcessEventIndex = " << std::dec
            << Off::InSDK::ProcessEvent::PEIndex << ";\n\n";

        out << "// Encrypted globals: Valorant deploys N parallel encrypted-slot ciphers,\n";
        out << "// one per protected global pointer. They share the same 7-state algorithm\n";
        out << "// (MAGIC 0x2545F4914F6CDD1D) but each owns an independent state struct.\n";
        out << "// Two are surfaced here:\n";
        out << "//   1. GObjects -- FUObjectArray* (cipher sub_EA1980 / sub_3638AC0)\n";
        out << "//   2. GEngine  -- UEngine*       (cipher sub_9DAF50, 180+ inlined readers)\n";
        out << "// FName decrypt is a SEPARATE path: simple per-byte XOR with a key recovered\n";
        out << "// from the FNamePool's first entry. See recover_fname_key() below.\n";
        const bool gengineDrift =
            Valorant::gEngineStateRVA != Valorant::kGEngineStateRVA ||
            Valorant::gEngineKeyRVA   != Valorant::kGEngineKeyRVA;
        const char* gengineSource = gengineDrift ? "sigscan" : "hardcoded";
        out << "/// RVA of the 7-qword GEngine encrypted slot cipher state array.\n";
        if (gengineDrift)
            out << "/// source=sigscan  fallback=0x" << std::hex << Valorant::kGEngineStateRVA
                << std::dec << "  DRIFT (bump Decryption.h fallback)\n";
        else
            EmitSourceLine(out, gengineSource);
        out << "constexpr uint32_t GEngineState    = 0x" << std::hex
            << Valorant::gEngineStateRVA << std::dec << ";\n";
        out << "/// RVA of the uint32 GEngine encrypted slot cipher key (= GEngineState + 0x38).\n";
        if (gengineDrift)
            out << "/// source=sigscan  fallback=0x" << std::hex << Valorant::kGEngineKeyRVA
                << std::dec << "  DRIFT (bump Decryption.h fallback)\n";
        else
            EmitSourceLine(out, gengineSource);
        out << "constexpr uint32_t GEngineKey      = 0x" << std::hex
            << Valorant::gEngineKeyRVA << std::dec << ";\n\n";

        // ------------------------------------------------------------------ //
        // Function Pointers
        // ------------------------------------------------------------------ //
        out << "// ============== Function Pointers ==============\n\n";

        out << "/// RVA of UObject::ProcessEvent from the module base.\n";
        EmitSourceLine(out, "upstream");
        out << "constexpr uint32_t ProcessEvent      = 0x" << std::hex
            << Off::InSDK::ProcessEvent::PEOffset << std::dec << ";\n";
        out << "/// RVA of FName::AppendString (AppendNameToString) from the module base.\n";
        EmitSourceLine(out, "upstream");
        out << "constexpr uint32_t AppendString      = 0x" << std::hex
            << Off::InSDK::Name::AppendNameToString << std::dec << ";\n";
        out << "/// RVA of StaticFindObject -- TODO: locate via UE-standard signature scan.\n";
        EmitSourceLine(out, "hardcoded");
        out << "constexpr uint32_t StaticFindObject  = 0x" << std::hex
            << TodoOffsets::kStaticFindObject << std::dec << ";\n";
        out << "/// RVA of StaticLoadObject -- TODO: locate via UE-standard signature scan.\n";
        EmitSourceLine(out, "missing", {}, false, 0, "StaticLoadObject");
        out << "constexpr uint32_t StaticLoadObject  = 0x" << std::hex
            << TodoOffsets::kStaticLoadObject << std::dec << ";\n";
        out << "/// RVA of FMemory::Malloc -- TODO: locate via UE-standard signature scan.\n";
        EmitSourceLine(out, "missing", {}, false, 0, "FMemoryMalloc");
        out << "constexpr uint32_t FMemoryMalloc     = 0x" << std::hex
            << TodoOffsets::kFMemoryMalloc << std::dec << ";\n";
        out << "/// RVA of bone-matrix getter -- TODO: locate via vtable/xref pattern scan.\n";
        EmitSourceLine(out, "missing", {}, false, 0, "BoneMatrix");
        out << "constexpr uint32_t BoneMatrix        = 0x" << std::hex
            << TodoOffsets::kBoneMatrix << std::dec << ";\n";

        // UFunction-reflected game functions
        auto EmitUFuncConst = [&](const char* constName, uint32_t rva,
                                  const std::string& fullName,
                                  const char* primaryTried, const char* altTried = nullptr)
        {
            const bool found  = (rva != 0);
            const char* src   = found ? "reflection" : "missing";

            if (found)
                EmitSourceLine(out, src, fullName);
            else
            {
                // Emit tried= list for missing entries
                out << "/// source=missing  tried=[\"" << primaryTried << "\"";
                if (altTried)
                    out << ",\"" << altTried << "\"";
                out << "]\n";
            }
            out << "constexpr uint32_t " << constName << " = 0x" << std::hex << rva << std::dec << ";\n";
        };

        out << "/// RVA of SetOutlineMode UFunction.\n";
        EmitUFuncConst("SetOutlineMode   ", Valorant::GameFunctions::SetOutlineMode,
                       Valorant::GameFunctions::SetOutlineModeFullName,
                       "SetOutlineMode", "GetAresOutlineMode");
        out << "/// RVA of PlayFinisher UFunction.\n";
        EmitUFuncConst("PlayFinisher     ", Valorant::GameFunctions::PlayFinisher,
                       Valorant::GameFunctions::PlayFinisherFullName,
                       "PlayFinisher", "OnFinisherTriggered");
        out << "/// RVA of GetSpreadValues UFunction.\n";
        EmitUFuncConst("GetSpreadValues  ", Valorant::GameFunctions::GetSpreadValues,
                       Valorant::GameFunctions::GetSpreadValuesFullName,
                       "GetSpreadValues");
        out << "/// RVA of GetSpreadAngles UFunction.\n";
        EmitUFuncConst("GetSpreadAngles  ", Valorant::GameFunctions::GetSpreadAngles,
                       Valorant::GameFunctions::GetSpreadAnglesFullName,
                       "GetSpreadAngles");
        out << "/// RVA of ToVectorNormalize UFunction.\n";
        EmitUFuncConst("ToVectorNormalize", Valorant::GameFunctions::ToVectorNormalize,
                       Valorant::GameFunctions::ToVectorNormalizeFullName,
                       "ToVectorNormalize");
        out << "/// RVA of ToAngleNormalize UFunction.\n";
        EmitUFuncConst("ToAngleNormalize ", Valorant::GameFunctions::ToAngleNormalize,
                       Valorant::GameFunctions::ToAngleNormalizeFullName,
                       "ToAngleNormalize");
        out << "/// RVA of GetFiringLocAndDir UFunction.\n";
        EmitUFuncConst("GetFiringLocAndDir", Valorant::GameFunctions::GetFiringLocAndDir,
                       Valorant::GameFunctions::GetFiringLocAndDirFullName,
                       "GetFiringLocAndDir", "GetFiringLocationAndDirection");
        out << "\n";

        // ------------------------------------------------------------------ //
        // GObjects Decrypt
        // ------------------------------------------------------------------ //
        out << "// ============== GObjects Decrypt ==============\n\n";

        out << "/// Rotate-left 64-bit helper used by decrypt_gobjects().\n";
        out << "__forceinline uint64_t rol64(uint64_t v, uint32_t n)\n";
        out << "{\n";
        out << "    n &= 63;\n";
        out << "    if (n == 0) return v;\n";
        out << "    return (v << n) | (v >> (64 - n));\n";
        out << "}\n\n";

        out << "/// Rotate-right 64-bit helper used by decrypt_gobjects().\n";
        out << "__forceinline uint64_t ror64(uint64_t v, uint32_t n)\n";
        out << "{\n";
        out << "    n &= 63;\n";
        out << "    if (n == 0) return v;\n";
        out << "    return (v >> n) | (v << (64 - n));\n";
        out << "}\n\n";

        out << "/// Bit-reversal stage 1: swap adjacent bits via 0xAAAA... mask.\n";
        out << "__forceinline uint64_t stage1(uint64_t v) { return (v >> 1) ^ (((v >> 1) ^ (v << 1)) & 0xAAAAAAAAAAAAAAAAULL); }\n";
        out << "/// Bit-reversal stage 2: swap 2-bit groups via 0xCCCC... mask.\n";
        out << "__forceinline uint64_t stage2(uint64_t v) { return (v >> 2) ^ (((v >> 2) ^ (v << 2)) & 0xCCCCCCCCCCCCCCCCULL); }\n";
        out << "/// Bit-reversal stage 3: swap nibbles via 0xF0F0... mask.\n";
        out << "__forceinline uint64_t stage3(uint64_t v) { return (v >> 4) ^ (((v >> 4) ^ (v << 4)) & 0xF0F0F0F0F0F0F0F0ULL); }\n";
        out << "/// Bit-reversal stage 4: swap bytes via 0xFF00... mask.\n";
        out << "__forceinline uint64_t stage4(uint64_t v) { return (v >> 8) ^ (((v >> 8) ^ (v << 8)) & 0xFF00FF00FF00FF00ULL); }\n";
        out << "/// Full 64-bit bit-reversal: pipeline of stages 1-4 followed by ror32.\n";
        out << "__forceinline uint64_t bitrev64(uint64_t v) { return ror64(stage4(stage3(stage2(stage1(v)))), 32); }\n\n";

        out << "/// Reads GObjectsState[7] + GObjectsKey from the live module and returns\n";
        out << "/// the decrypted FUObjectArray base pointer (ported from sub_EA1980).\n";
        out << "__forceinline uint64_t decrypt_gobjects(uintptr_t module_base)\n";
        out << "{\n";
        out << "    constexpr uint64_t kMagic = 0x2545F4914F6CDD1DULL;\n";
        out << "    const uint64_t* statePtr = reinterpret_cast<const uint64_t*>(module_base + GObjectsState);\n";
        out << "    const uint32_t  key      = *reinterpret_cast<const uint32_t*>(module_base + GObjectsKey);\n";
        out << "    uint64_t state[7];\n";
        out << "    for (int i = 0; i < 7; ++i) state[i] = statePtr[i];\n\n";
        out << "    const uint32_t mix  = key ^ (((key ^ (key >> 15)) >> 12)) ^ (key << 25);\n";
        out << "    const uint64_t hash = kMagic * static_cast<uint64_t>(mix);\n";
        out << "    const uint32_t hi   = static_cast<uint32_t>(hash >> 32);\n";
        out << "    const uint32_t idx  = static_cast<uint32_t>(hash % 7ULL);\n";
        out << "    uint64_t v = state[idx];\n\n";
        out << "    switch (idx)\n";
        out << "    {\n";
        out << "    case 0:  v ^= static_cast<uint64_t>(hi); break;\n";
        out << "    case 1:  { uint32_t a = ((hi + 2 * idx) % 63) + 1; v = static_cast<uint64_t>(static_cast<uint32_t>(hi + idx)) + rol64(v, a); break; }\n";
        out << "    case 2:  v = (~v) - static_cast<uint64_t>(static_cast<uint32_t>(hi + idx)); break;\n";
        out << "    case 3:  { uint32_t a = ((hi + idx)     % 63) + 1; v = ror64(bitrev64(v), a); break; }\n";
        out << "    case 4:  v += static_cast<uint64_t>(static_cast<uint32_t>(hi + 2 * idx)) + static_cast<uint64_t>(static_cast<uint32_t>(hi + idx)); break;\n";
        out << "    case 5:  { uint32_t a = ((hi + idx)     % 63) + 1; v = rol64(stage1(v), a); break; }\n";
        out << "    case 6:  { uint32_t a = ((hi + idx)     % 63) + 1; v = ror64(static_cast<uint64_t>(static_cast<uint32_t>(hi + 2 * idx)) + v, a); break; }\n";
        out << "    }\n\n";
        out << "    return v ^ static_cast<uint64_t>(key);\n";
        out << "}\n\n";

        // ------------------------------------------------------------------ //
        // FName Decrypt
        // ------------------------------------------------------------------ //
        out << "// ============== FName Decrypt ==============\n\n";

        out << "/// Known-plaintext XOR mask derived from the encoded \"None\" entry.\n";
        out << "/// XOR'ing the encrypted first-entry name dword against this recovers\n";
        out << "/// the per-patch FName key ('N'^'o'^'n'^'e' bytes + encoder length step).\n";
        out << "constexpr uint32_t kFNameNoneMask = 0x616A6B4A;\n\n";

        out << "/// Recover the FName XOR key from FNamePool's first entry (\"None\").\n";
        out << "/// fname_pool_base is the value at *(module_base + FNamePool).\n";
        out << "__forceinline uint32_t recover_fname_key(uintptr_t fname_pool_base)\n";
        out << "{\n";
        out << "    const uintptr_t chunk0 = *reinterpret_cast<uintptr_t*>(fname_pool_base + 0x10);\n";
        out << "    if (!chunk0) return 0;\n";
        out << "    // First entry is \"None\" -- its 4 encrypted name bytes start at +6 from\n";
        out << "    // the entry base; XOR with kFNameNoneMask gives the key.\n";
        out << "    const uintptr_t entry  = chunk0 + 12;  // header at +0..+5\n";
        out << "    const uint32_t  enc4   = *reinterpret_cast<uint32_t*>(entry + 6);\n";
        out << "    return enc4 ^ kFNameNoneMask;\n";
        out << "}\n\n";

        out << "/// Decrypt an FName entry's bytes in-place. key must come from\n";
        out << "/// recover_fname_key(). buf must hold `len` bytes copied from\n";
        out << "/// (entry_address + 6), i.e. past the 6-byte FName entry header.\n";
        out << "__forceinline void fname_decrypt_bytes(uint8_t* buf, uint16_t len, uint32_t key)\n";
        out << "{\n";
        out << "    for (uint16_t i = 0; i < len; ++i)\n";
        out << "    {\n";
        out << "        const uint8_t k = static_cast<uint8_t>((key >> ((i & 3) * 8)) & 0xFF);\n";
        out << "        buf[i] ^= static_cast<uint8_t>(len) ^ k;\n";
        out << "    }\n";
        out << "}\n\n";

        // ------------------------------------------------------------------ //
        // GEngine Encrypted Slot Cipher (sub_9DAF50)
        // ------------------------------------------------------------------ //
        out << "// ============== GEngine Encrypted Slot Cipher (sub_9DAF50) ==============\n\n";
        out << "// Decrypts the global UEngine* pointer (Valorant's GEngine slot).\n";
        out << "// 180+ sites in the game binary inline this exact 7-state cipher to\n";
        out << "// dereference GEngine; the algorithm is identical to the GObjects cipher\n";
        out << "// above but reads from a parallel state struct. Useful for any consumer\n";
        out << "// that needs world/viewport access without scanning the heap.\n\n";

        out << "/// Reads GEngineState[7] + GEngineKey from the live module and returns\n";
        out << "/// the decrypted mask qword (ported from sub_9DAF50, read path).\n";
        out << "__forceinline uint64_t decrypt_gengine(uintptr_t module_base)\n";
        out << "{\n";
        out << "    constexpr uint64_t kMagic = 0x2545F4914F6CDD1DULL;\n";
        out << "    const uint64_t* statePtr = reinterpret_cast<const uint64_t*>(module_base + GEngineState);\n";
        out << "    const uint32_t  key      = *reinterpret_cast<const uint32_t*>(module_base + GEngineKey);\n";
        out << "    uint64_t state[7];\n";
        out << "    for (int i = 0; i < 7; ++i) state[i] = statePtr[i];\n\n";
        out << "    const uint32_t mix  = key ^ (((key ^ (key >> 15)) >> 12)) ^ (key << 25);\n";
        out << "    const uint64_t hash = kMagic * static_cast<uint64_t>(mix);\n";
        out << "    const uint32_t hi   = static_cast<uint32_t>(hash >> 32);\n";
        out << "    const uint32_t idx  = static_cast<uint32_t>(hash % 7ULL);\n";
        out << "    uint64_t v = state[idx];\n\n";
        out << "    switch (idx)\n";
        out << "    {\n";
        out << "    case 0: v = ~(v + static_cast<uint64_t>(static_cast<uint32_t>(hi - 1))); break;\n";
        out << "    case 1: v = stage1(v ^ static_cast<uint64_t>(~static_cast<uint32_t>(hi + 2 * idx))); break;\n";
        out << "    case 2: v = ~stage1(v); break;\n";
        out << "    case 3: v = stage1(v + static_cast<uint64_t>(static_cast<uint32_t>(hi + 2 * idx))); break;\n";
        out << "    case 4: v = bitrev64(stage1(v)); break;\n";
        out << "    case 5: { uint32_t a1 = ((hi + 2 * idx) % 63) + 1; uint32_t a2 = ((hi + idx) % 63) + 1; v = rol64(rol64(v, a1), a2); break; }\n";
        out << "    case 6: { uint32_t a  = ((hi + 2 * idx) % 63) + 1; v = bitrev64(ror64(v, a)); break; }\n";
        out << "    }\n\n";
        out << "    return v ^ static_cast<uint64_t>(key);\n";
        out << "}\n\n";

        // ------------------------------------------------------------------ //
        // UE Stable Offsets
        // ------------------------------------------------------------------ //
        out << "// ============== UE Stable Offsets ==============\n\n";
        out << "/// UE class member offsets verified against Engine_classes.hpp from the\n";
        out << "/// 12.09 SDK dump. These are UE-source-level constants and do not change\n";
        out << "/// between Valorant patches unless Epic restructures the class layout.\n";
        out << "namespace UEOffsets\n";
        out << "{\n\n";

        out << "    /// Offset of UGameViewportClient* GameViewport within UEngine.\n";
        out << "    constexpr uint32_t UEngine_GameViewport                    = 0x0BD0;\n";
        out << "    /// Offset of UWorld* World within UGameViewportClient.\n";
        out << "    constexpr uint32_t UGameViewportClient_World               = 0x0080;\n";
        out << "    /// Offset of UGameInstance* GameInstance within UGameViewportClient.\n";
        out << "    /// (UEngine itself has no direct GameInstance member; this is the path.)\n";
        out << "    constexpr uint32_t UGameViewportClient_GameInstance        = 0x0088;\n";
        out << "    /// Offset of TArray<ULocalPlayer*> LocalPlayers within UGameInstance.\n";
        out << "    constexpr uint32_t UGameInstance_LocalPlayers              = 0x0040;\n";
        out << "    /// Offset of APlayerController* PlayerController within ULocalPlayer.\n";
        out << "    constexpr uint32_t ULocalPlayer_PlayerController           = 0x0038;\n";
        out << "    /// Offset of APawn* AcknowledgedPawn within APlayerController.\n";
        out << "    constexpr uint32_t APlayerController_AcknowledgedPawn      = 0x0518;\n";
        out << "    /// Offset of APlayerCameraManager* PlayerCameraManager within APlayerController.\n";
        out << "    constexpr uint32_t APlayerController_PlayerCameraManager   = 0x0528;\n";
        out << "    /// Offset of FCameraCacheEntry CameraCachePrivate within APlayerCameraManager.\n";
        out << "    constexpr uint32_t APlayerCameraManager_CameraCachePrivate = 0x17B0;\n";
        out << "    /// Offset of ULevel* PersistentLevel within UWorld.\n";
        out << "    constexpr uint32_t UWorld_PersistentLevel                  = 0x0038;\n";
        out << "    /// Offset of TArray<ULevel*> Levels within UWorld.\n";
        out << "    constexpr uint32_t UWorld_Levels                           = 0x0190;\n";
        out << "    /// Offset of UGameInstance* OwningGameInstance within UWorld.\n";
        out << "    constexpr uint32_t UWorld_OwningGameInstance               = 0x01D8;\n";
        out << "    /// Offset of TArray<AActor*> Actors within ULevel.\n";
        out << "    constexpr uint32_t ULevel_Actors                           = 0x00A0;\n";
        out << "    /// Offset of UWorld* OwningWorld within ULevel (back-ref for validation).\n";
        out << "    constexpr uint32_t ULevel_OwningWorld                      = 0x00C0;\n";
        out << "    /// Offset of UClass* ClassPrivate within UObject.\n";
        out << "    constexpr uint32_t UObject_ClassPrivate                    = 0x0010;\n";
        out << "    /// Offset of FName NamePrivate within UObject.\n";
        out << "    constexpr uint32_t UObject_NamePrivate                     = 0x0018;\n";
        out << "    /// Offset of UStruct* SuperStruct (parent class chain) within UStruct.\n";
        out << "    constexpr uint32_t UStruct_SuperStruct                     = 0x0048;\n\n";

        out << "} // namespace UEOffsets\n\n";

        // ------------------------------------------------------------------ //
        // Usage example
        // ------------------------------------------------------------------ //
        out << "/*\n";
        out << " * Usage example -- consumer flow against the live game.\n";
        out << " * Pseudocode; does not need to compile as-is.\n";
        out << " *\n";
        out << " *   uintptr_t base = GetModuleBase(\"VALORANT-Win64-Shipping.exe\");\n";
        out << " *\n";
        out << " *   // 1. Decrypt GObjects to get the FUObjectArray base.\n";
        out << " *   uintptr_t fuoa = (uintptr_t)decrypt_gobjects(base);\n";
        out << " *\n";
        out << " *   // 2. Walk GObjects to find a non-default UEngine instance. The\n";
        out << " *   //    static GWorld slot is zeroed in Valorant, so the supported path\n";
        out << " *   //    is UEngine -> GameViewport -> World. Cache `engine` after the\n";
        out << " *   //    first hit -- it does not move for the process lifetime.\n";
        out << " *   uintptr_t chunks = ReadPtr(fuoa + 0x00);\n";
        out << " *   int32_t   num    = ReadI32(fuoa + 0x14);\n";
        out << " *   uintptr_t engine = 0;\n";
        out << " *   for (int32_t i = 0; i < num && !engine; ++i) {\n";
        out << " *       uintptr_t chunk = ReadPtr(chunks + (i >> 16) * 8);\n";
        out << " *       uintptr_t obj   = ReadPtr(chunk  + (i & 0xFFFF) * 0x18);\n";
        out << " *       // FUObjectItem stride = 0x18; Object* lives at +0.\n";
        out << " *       if (obj && IsUEngineSubclassNonDefault(obj)) engine = obj;\n";
        out << " *   }\n";
        out << " *\n";
        out << " *   // 3. UEngine -> GameViewport -> World.\n";
        out << " *   uintptr_t viewport = ReadPtr(engine   + UEOffsets::UEngine_GameViewport);\n";
        out << " *   uintptr_t world    = ReadPtr(viewport + UEOffsets::UGameViewportClient_World);\n";
        out << " *\n";
        out << " *   // 4. Recover the FName key once (stable per session).\n";
        out << " *   uintptr_t pool      = ReadPtr(base + FNamePool);\n";
        out << " *   uint32_t  fname_key = recover_fname_key(pool);\n";
        out << " *\n";
        out << " *   // 5. Walk actors and resolve their names.\n";
        out << " *   uintptr_t level       = ReadPtr(world + UEOffsets::UWorld_PersistentLevel);\n";
        out << " *   uintptr_t actors_data = ReadPtr(level + UEOffsets::ULevel_Actors);\n";
        out << " *   int32_t   actors_num  = ReadI32(level + UEOffsets::ULevel_Actors + 8);\n";
        out << " *   for (int32_t i = 0; i < actors_num; ++i) {\n";
        out << " *       uintptr_t actor = ReadPtr(actors_data + i * 8);\n";
        out << " *       if (!actor) continue;\n";
        out << " *       uint32_t name_idx = ReadU32(actor + UEOffsets::UObject_NamePrivate);\n";
        out << " *       // Look up name_idx in `pool` (chunk = idx>>16, slot = (idx&0xFFFF)*4),\n";
        out << " *       // read entry header at +4 for length, copy `len` bytes from entry+6,\n";
        out << " *       // then call fname_decrypt_bytes(buf, len, fname_key).\n";
        out << " *   }\n";
        out << " */\n\n";

        out << "} // namespace ValorantSDK\n";
        out.close();

        std::cerr << "[Valorant] Wrote " << target.string() << "\n";

        // ------------------------------------------------------------------ //
        // Emit ValorantOffsets.json alongside the header
        // ------------------------------------------------------------------ //
        WriteOffsetsJson(OutputFolder);
    }

    void WriteOffsetsJson(const fs::path& OutputFolder)
    {
        using json = nlohmann::json;

        const fs::path target = OutputFolder / "ValorantOffsets.json";

        // Pre-compute drift flags
        const bool gObjectsStateDrift = (Valorant::gObjectsStateRVA != Valorant::kGObjectsStateRVA);
        const bool gObjectsKeyDrift   = (Valorant::gObjectsKeyRVA   != Valorant::kGObjectsKeyRVA);

        // Helper: build a global-pointer entry
        auto MakeGlobalPtr = [](const std::string& rva, const char* source,
                                const char* confidence,
                                const std::string& fallbackRva = {},
                                bool drift = false) -> json
        {
            json obj;
            obj["rva"]        = rva;
            obj["source"]     = source;
            obj["confidence"] = confidence;
            if (!fallbackRva.empty())
                obj["fallback_rva"] = fallbackRva;
            if (drift)
                obj["drift"] = true;
            return obj;
        };

        // Helper: build a function-pointer entry
        auto MakeFuncPtr = [](const std::string& rva, const char* source,
                              const char* confidence,
                              const std::string& fullName = {}) -> json
        {
            json obj;
            obj["rva"]        = rva;
            obj["source"]     = source;
            obj["confidence"] = confidence;
            if (!fullName.empty())
                obj["full_name"] = fullName;
            return obj;
        };

        // Helper: missing function entry with tried= list
        auto MakeMissing = [](std::initializer_list<const char*> tried) -> json
        {
            json obj;
            obj["rva"]        = "0x0";
            obj["source"]     = "missing";
            obj["confidence"] = "n/a";
            json triedArr = json::array();
            for (const char* t : tried)
                triedArr.push_back(t);
            obj["tried"] = triedArr;
            return obj;
        };

        // UFunction entry: reflection if found, missing otherwise
        auto MakeUFunc = [&](uint32_t rva, const std::string& fullName,
                             std::initializer_list<const char*> tried) -> json
        {
            if (rva != 0)
                return MakeFuncPtr(HexRva(rva), "reflection", "high", fullName);
            return MakeMissing(tried);
        };

        json root;

        // -- build section
        {
            json build;
            build["game_name"]    = Settings::Generator::GameName;
            build["game_version"] = Settings::Generator::GameVersion;
            build["generated_at"] = GetUtcTimestamp();
            root["build"] = std::move(build);
        }

        // -- global_pointers section
        {
            json gp;
            gp["GWorld"] = MakeGlobalPtr("0x0", "stripped", "n/a");
            gp["FNamePool"] = MakeGlobalPtr(
                HexRva(static_cast<uint32_t>(Off::InSDK::NameArray::GNames)),
                "upstream", "high");
            gp["GObjectsState"] = MakeGlobalPtr(
                HexRva(Valorant::gObjectsStateRVA),
                "sigscan", "high",
                HexRva(Valorant::kGObjectsStateRVA),
                gObjectsStateDrift);
            gp["GObjectsKey"] = MakeGlobalPtr(
                HexRva(Valorant::gObjectsKeyRVA),
                "sigscan", "high",
                HexRva(Valorant::kGObjectsKeyRVA),
                gObjectsKeyDrift);
            gp["GEngineState"] = MakeGlobalPtr(
                HexRva(Valorant::gEngineStateRVA),
                "hardcoded", "medium");
            gp["GEngineKey"] = MakeGlobalPtr(
                HexRva(Valorant::gEngineKeyRVA),
                "hardcoded", "medium");

            json peIdx;
            peIdx["value"]      = Off::InSDK::ProcessEvent::PEIndex;
            peIdx["source"]     = "upstream";
            peIdx["confidence"] = "high";
            gp["ProcessEventIndex"] = std::move(peIdx);

            root["global_pointers"] = std::move(gp);
        }

        // -- function_pointers section
        {
            json fp;
            fp["ProcessEvent"] = MakeFuncPtr(
                HexRva(static_cast<uint32_t>(Off::InSDK::ProcessEvent::PEOffset)),
                "upstream", "high");
            fp["AppendString"] = MakeFuncPtr(
                HexRva(static_cast<uint32_t>(Off::InSDK::Name::AppendNameToString)),
                "upstream", "high");
            fp["StaticFindObject"] = MakeFuncPtr(
                HexRva(TodoOffsets::kStaticFindObject),
                "hardcoded", "medium");
            fp["StaticLoadObject"] = MakeMissing({"StaticLoadObject"});
            fp["FMemoryMalloc"]    = MakeMissing({"FMemoryMalloc"});
            fp["BoneMatrix"]       = MakeMissing({"BoneMatrix"});
            fp["SetOutlineMode"]   = MakeUFunc(
                Valorant::GameFunctions::SetOutlineMode,
                Valorant::GameFunctions::SetOutlineModeFullName,
                {"SetOutlineMode", "GetAresOutlineMode"});
            fp["PlayFinisher"]     = MakeUFunc(
                Valorant::GameFunctions::PlayFinisher,
                Valorant::GameFunctions::PlayFinisherFullName,
                {"PlayFinisher", "OnFinisherTriggered"});
            fp["GetSpreadValues"]  = MakeUFunc(
                Valorant::GameFunctions::GetSpreadValues,
                Valorant::GameFunctions::GetSpreadValuesFullName,
                {"GetSpreadValues"});
            fp["GetSpreadAngles"]  = MakeUFunc(
                Valorant::GameFunctions::GetSpreadAngles,
                Valorant::GameFunctions::GetSpreadAnglesFullName,
                {"GetSpreadAngles"});
            fp["ToVectorNormalize"] = MakeUFunc(
                Valorant::GameFunctions::ToVectorNormalize,
                Valorant::GameFunctions::ToVectorNormalizeFullName,
                {"ToVectorNormalize"});
            fp["ToAngleNormalize"] = MakeUFunc(
                Valorant::GameFunctions::ToAngleNormalize,
                Valorant::GameFunctions::ToAngleNormalizeFullName,
                {"ToAngleNormalize"});
            fp["GetFiringLocAndDir"] = MakeUFunc(
                Valorant::GameFunctions::GetFiringLocAndDir,
                Valorant::GameFunctions::GetFiringLocAndDirFullName,
                {"GetFiringLocAndDir", "GetFiringLocationAndDirection"});

            root["function_pointers"] = std::move(fp);
        }

        // -- ue_offsets section (sdk-stable UE class layout constants)
        {
            json ue;
            auto FmtOff = [](uint32_t v) -> std::string { return HexRva(v); };
            ue["UEngine_GameViewport"]                    = FmtOff(0x0BD0);
            ue["UGameViewportClient_World"]               = FmtOff(0x0080);
            ue["UGameViewportClient_GameInstance"]        = FmtOff(0x0088);
            ue["UGameInstance_LocalPlayers"]              = FmtOff(0x0040);
            ue["ULocalPlayer_PlayerController"]           = FmtOff(0x0038);
            ue["APlayerController_AcknowledgedPawn"]      = FmtOff(0x0518);
            ue["APlayerController_PlayerCameraManager"]   = FmtOff(0x0528);
            ue["APlayerCameraManager_CameraCachePrivate"] = FmtOff(0x17B0);
            ue["UWorld_PersistentLevel"]                  = FmtOff(0x0038);
            ue["UWorld_Levels"]                           = FmtOff(0x0190);
            ue["UWorld_OwningGameInstance"]               = FmtOff(0x01D8);
            ue["ULevel_Actors"]                           = FmtOff(0x00A0);
            ue["ULevel_OwningWorld"]                      = FmtOff(0x00C0);
            ue["UObject_ClassPrivate"]                    = FmtOff(0x0010);
            ue["UObject_NamePrivate"]                     = FmtOff(0x0018);
            ue["UStruct_SuperStruct"]                     = FmtOff(0x0048);
            root["ue_offsets"] = std::move(ue);
        }

        std::ofstream jout(target);
        if (!jout.is_open())
        {
            std::cerr << "[Valorant] Failed to open " << target << " for write.\n";
            return;
        }
        jout << root.dump(2) << "\n";
        jout.close();

        std::cerr << "[Valorant] Wrote " << target.string() << "\n";
    }
}
